apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-price-prediction
  labels:
    app: house-price-prediction
spec:
  replicas: 3
  selector:
    matchLabels:
      app: house-price-prediction
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: house-price-prediction
    spec:
      containers:
        - name: house-price-prediction
          image: alpegon/house-price-prediction
          imagePullPolicy: Always
          ports:
            - containerPort: 80
